services:
  react-app:
    build:
      context: ./llm-wordgame
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - llm-server

  llm-server:
    build:
      context: ./llm-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"