import { word } from "../types/types";

const words: word[] = [
  { 'word': 'love', 'type': 'abstract', 'bannedWords': ['hate', 'romance', 'affection'] },
  { 'word': 'truth', 'type': 'abstract', 'bannedWords': ['lie', 'falsehood', 'honesty'] },
  { 'word': 'pleasure', 'type': 'abstract', 'bannedWords': ['pain', 'enjoyment', 'satisfaction'] },
  { 'word': 'chair', 'type': 'simple', 'bannedWords': ['table', 'sofa', 'furniture'] },
  { 'word': 'desk', 'type': 'simple', 'bannedWords': ['table', 'chair', 'furniture'] },
  { 'word': 'forgiveness', 'type': 'abstract', 'bannedWords': ['revenge', 'apology', 'pardon'] },
  { 'word': 'happiness', 'type': 'abstract', 'bannedWords': ['sadness', 'joy', 'contentment'] },
  { 'word': 'television', 'type': 'simple', 'bannedWords': ['tv', 'monitor', 'screen'] },
  { 'word': 'bag', 'type': 'simple', 'bannedWords': ['backpack', 'purse', 'sack'] },
  { 'word': 'empathy', 'type': 'abstract', 'bannedWords': ['sympathy', 'compassion', 'understanding'] },
  { 'word': 'container', 'type': 'simple', 'bannedWords': ['box', 'jar', 'vessel'] },
  { 'word': 'lamp', 'type': 'simple', 'bannedWords': ['light', 'bulb', 'fixture'] },
  { 'word': 'reason', 'type': 'abstract', 'bannedWords': ['logic', 'cause', 'motive'] },
  { 'word': 'pencil', 'type': 'simple', 'bannedWords': ['pen', 'crayon', 'writing'] },
  { 'word': 'prejudice', 'type': 'abstract', 'bannedWords': ['bias', 'discrimination', 'racism'] },
  { 'word': 'spoon', 'type': 'simple', 'bannedWords': ['fork', 'knife', 'utensil'] },
  { 'word': 'portrait', 'type': 'simple', 'bannedWords': ['painting', 'picture', 'photograph'] },
  { 'word': 'imagination', 'type': 'abstract', 'bannedWords': ['creativity', 'fantasy', 'innovation'] },
  { 'word': 'freedom', 'type': 'abstract', 'bannedWords': ['liberty', 'independence', 'autonomy'] },
  { 'word': 'nature', 'type': 'simple', 'bannedWords': ['environment', 'outdoors', 'wildlife'] },
  { 'word': 'empathy', 'type': 'abstract', 'bannedWords': ['sympathy', 'compassion', 'understanding'] },
  { 'word': 'pleasure', 'type': 'abstract', 'bannedWords': ['pain', 'enjoyment', 'satisfaction'] },
  { 'word': 'justice', 'type': 'abstract', 'bannedWords': ['fairness', 'law', 'equity'] },
  { 'word': 'courage', 'type': 'abstract', 'bannedWords': ['bravery', 'fearlessness', 'valor'] },
  { 'word': 'book', 'type': 'simple', 'bannedWords': ['novel', 'read', 'pages'] },
  { 'word': 'window', 'type': 'simple', 'bannedWords': ['glass', 'pane', 'view'] },
  { 'word': 'music', 'type': 'abstract', 'bannedWords': ['song', 'melody', 'harmony'] },
  { 'word': 'computer', 'type': 'simple', 'bannedWords': ['laptop', 'PC', 'device'] },
  { 'word': 'friendship', 'type': 'abstract', 'bannedWords': ['companionship', 'relationship', 'bond'] },
  { 'word': 'garden', 'type': 'simple', 'bannedWords': ['plants', 'flowers', 'yard'] },
  { 'word': 'knowledge', 'type': 'abstract', 'bannedWords': ['wisdom', 'information', 'learning'] },
  { 'word': 'dream', 'type': 'abstract', 'bannedWords': ['sleep', 'vision', 'goal'] },
  { 'word': 'hope', 'type': 'abstract', 'bannedWords': ['wish', 'desire', 'aspiration'] },
  { 'word': 'car', 'type': 'simple', 'bannedWords': ['automobile', 'vehicle', 'drive'] },
  { 'word': 'river', 'type': 'simple', 'bannedWords': ['stream', 'water', 'flow'] },
  { 'word': 'patience', 'type': 'abstract', 'bannedWords': ['tolerance', 'endurance', 'perseverance'] },
  { 'word': 'mountain', 'type': 'simple', 'bannedWords': ['hill', 'peak', 'summit'] },
  { 'word': 'honesty', 'type': 'abstract', 'bannedWords': ['truthfulness', 'integrity', 'sincerity'] },
  { 'word': 'ocean', 'type': 'simple', 'bannedWords': ['sea', 'water', 'wave'] },
  { 'word': 'loyalty', 'type': 'abstract', 'bannedWords': ['faithfulness', 'allegiance', 'devotion'] },
  { 'word': 'forest', 'type': 'simple', 'bannedWords': ['woods', 'trees', 'jungle'] },
  { 'word': 'wisdom', 'type': 'abstract', 'bannedWords': ['knowledge', 'insight', 'sagacity'] },
  { 'word': 'city', 'type': 'simple', 'bannedWords': ['town', 'urban', 'metropolis'] },
  { 'word': 'faith', 'type': 'abstract', 'bannedWords': ['belief', 'trust', 'confidence'] },
  { 'word': 'island', 'type': 'simple', 'bannedWords': ['land', 'water', 'sea'] },
  { 'word': 'charity', 'type': 'abstract', 'bannedWords': ['donation', 'generosity', 'philanthropy'] },
  { 'word': 'bridge', 'type': 'simple', 'bannedWords': ['structure', 'span', 'crossing'] },
  { 'word': 'gratitude', 'type': 'abstract', 'bannedWords': ['thankfulness', 'appreciation', 'gratefulness'] },
  { 'word': 'desert', 'type': 'simple', 'bannedWords': ['sand', 'dune', 'arid'] },
  { 'word': 'humility', 'type': 'abstract', 'bannedWords': ['modesty', 'meekness', 'humbleness'] },
  { 'word': 'castle', 'type': 'simple', 'bannedWords': ['fortress', 'palace', 'stronghold'] },
  { 'word': 'ambition', 'type': 'abstract', 'bannedWords': ['goal', 'aspiration', 'drive'] },
];

export default words;